; Bambu A1 Mini 
bed_shape = 0x0,180x0,180x180,0x180
bed_temperature = 60
bottom_solid_layers = 4
bridge_speed = 25
cooling = 1
default_print_profile = 0.20mm QUALITY
extrusion_multiplier = 1
filament_diameter = 1.75
fill_density = 15%
first_layer_height = 0.2
gcode_flavor = marlin
infill_speed = 60
layer_height = 0.2
nozzle_diameter = 0.4
perimeters = 2
perimeter_speed = 45
printer_technology = FFF
retract_length = 0.8
retract_speed = 35
skirts = 1
support_material = 0
temperature = 205
travel_speed = 120
